kind: Deployment # or DaemonSet or StatefulSet

replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  - name: ENVIRONMENT
    value: production

containerName: app

annotations: {}

resources: {}
volumeMounts: []
volumes: []

nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext: {}
serviceAccount:
  name: default

configmap:
  enabled: false
  data: {}