

{{- if .Values.configMaps }}
{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "universal-app.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- if .binaryData }}
binaryData:
  {{- toYaml .binaryData | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}