{{- if eq .Values.kind "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "universal-app.fullname" . }}
  labels:
    {{- include "universal-app.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.job.backoffLimit }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
  {{- if .Values.job.completions }}
  completions: {{ .Values.job.completions }}
  {{- end }}
  {{- if .Values.job.parallelism }}
  parallelism: {{ .Values.job.parallelism }}
  {{- end }}
  {{- if .Values.job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  {{- end }}
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  {{- if .Values.job.suspend }}
  suspend: {{ .Values.job.suspend }}
  {{- end }}
  template:
    {{- include "universal-app.podTemplate" . | nindent 4 }}
{{- end }}

