{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "universal-app.fullname" . }}
  labels:
    {{- include "universal-app.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ .Values.statefulSet.serviceName | default (include "universal-app.fullname" .) | quote }}
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.statefulSet.podManagementPolicy }}
  podManagementPolicy: {{ .Values.statefulSet.podManagementPolicy }}
  {{- end }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.minReadySeconds }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "universal-app.selectorLabels" . | nindent 6 }}
  {{- with .Values.persistentVolumeClaims }}
  volumeClaimTemplates:
    {{- range . }}
    - metadata:
        name: {{ .name }}
        {{- with .labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{- with .accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .storageClassName }}
        storageClassName: {{ .storageClassName }}
        {{- end }}
        {{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .volumeMode }}
        volumeMode: {{ .volumeMode }}
        {{- end }}
        {{- with .dataSource }}
        dataSource:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
  {{- end }}
  template:
    {{- include "universal-app.podTemplate" . | nindent 4 }}
{{- end }}
